<a href="https://colab.research.google.com/github/macorony/NeuralNetwork/blob/main/building_models_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import torch
import torch.nn.functional as F

In [21]:
F.relu

<function torch.nn.functional.relu(input: torch.Tensor, inplace: bool = False) -> torch.Tensor>

In [2]:
class MiniNet(torch.nn.Module):
  def __init__(self):
    super(MiniNet, self).__init__()
    self.layer1 = torch.nn.Linear(100, 200)
    self.act = torch.nn.ReLU()
    self.layer2 = torch.nn.Linear(200, 10)
    self.softmax = torch.nn.Softmax()
  def forward(self, input):
    x = self.layer1(input)
    x = self.act(x)
    x = self.layer2(x)
    output = self.softmax(x)
    return output


In [3]:
smallNet = MiniNet()
print(smallNet)
print(smallNet.layer1)
print(smallNet.layer2)

MiniNet(
  (layer1): Linear(in_features=100, out_features=200, bias=True)
  (act): ReLU()
  (layer2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)
Linear(in_features=100, out_features=200, bias=True)
Linear(in_features=200, out_features=10, bias=True)


In [4]:
for param in smallNet.parameters():
  print(param)

Parameter containing:
tensor([[ 0.0233, -0.0119,  0.0370,  ...,  0.0835, -0.0283, -0.0558],
        [-0.0616,  0.0870,  0.0828,  ..., -0.0408,  0.0159,  0.0260],
        [ 0.0925, -0.0795,  0.0347,  ..., -0.0378,  0.0952,  0.0779],
        ...,
        [-0.0258, -0.0550, -0.0217,  ...,  0.0781,  0.0673, -0.0605],
        [-0.0084, -0.0029,  0.0138,  ...,  0.0410,  0.0745, -0.0690],
        [ 0.0432, -0.0448, -0.0772,  ..., -0.0486, -0.0785,  0.0577]],
       requires_grad=True)
Parameter containing:
tensor([-8.7652e-02, -2.0858e-02,  8.7824e-02,  7.4486e-02,  9.6734e-02,
         3.0688e-02, -3.6214e-02,  8.6933e-02,  7.5025e-02,  1.0094e-02,
        -6.0553e-03, -2.6720e-02, -6.3130e-02,  1.7750e-05, -5.9953e-02,
         4.9103e-02,  6.2169e-02,  6.4504e-02, -1.6529e-02,  6.6016e-02,
         9.8685e-02, -1.1230e-02, -6.2356e-03, -7.7069e-02, -4.2872e-03,
         1.7814e-02, -7.3394e-02, -8.0369e-02, -3.3907e-02, -5.9664e-02,
        -9.3133e-02,  7.8199e-02, -7.1225e-02, -7.9429e-0

In [5]:
for param in smallNet.layer1.parameters():
  print(param)

Parameter containing:
tensor([[ 0.0233, -0.0119,  0.0370,  ...,  0.0835, -0.0283, -0.0558],
        [-0.0616,  0.0870,  0.0828,  ..., -0.0408,  0.0159,  0.0260],
        [ 0.0925, -0.0795,  0.0347,  ..., -0.0378,  0.0952,  0.0779],
        ...,
        [-0.0258, -0.0550, -0.0217,  ...,  0.0781,  0.0673, -0.0605],
        [-0.0084, -0.0029,  0.0138,  ...,  0.0410,  0.0745, -0.0690],
        [ 0.0432, -0.0448, -0.0772,  ..., -0.0486, -0.0785,  0.0577]],
       requires_grad=True)
Parameter containing:
tensor([-8.7652e-02, -2.0858e-02,  8.7824e-02,  7.4486e-02,  9.6734e-02,
         3.0688e-02, -3.6214e-02,  8.6933e-02,  7.5025e-02,  1.0094e-02,
        -6.0553e-03, -2.6720e-02, -6.3130e-02,  1.7750e-05, -5.9953e-02,
         4.9103e-02,  6.2169e-02,  6.4504e-02, -1.6529e-02,  6.6016e-02,
         9.8685e-02, -1.1230e-02, -6.2356e-03, -7.7069e-02, -4.2872e-03,
         1.7814e-02, -7.3394e-02, -8.0369e-02, -3.3907e-02, -5.9664e-02,
        -9.3133e-02,  7.8199e-02, -7.1225e-02, -7.9429e-0

# Layer Types

In [13]:
linear = torch.nn.Linear(3,2)
x = torch.rand(1,3)
print(linear.weight)

Parameter containing:
tensor([[ 0.4122, -0.4587,  0.3181],
        [ 0.2280, -0.3029,  0.5445]], requires_grad=True)


In [11]:
for param in linear.parameters():
  print(param)

Parameter containing:
tensor([[ 0.0088, -0.5499, -0.0784],
        [ 0.1814,  0.2356, -0.0315]], requires_grad=True)
Parameter containing:
tensor([ 0.4821, -0.2158], requires_grad=True)


In [12]:
output = linear(x)
print(output)

tensor([[-0.0878,  0.1370]], grad_fn=<AddmmBackward0>)


In [22]:
class LeNet(torch.nn.Module):
  def __init__(self):
    super(LeNet, self).__init__()
    self.conv1 = torch.nn.Conv2d(1,6,5)
    self.conv2 = torch.nn.Conv2d(6,16,3)
    self.fc1 = torch.nn.Linear(16*6*6, 120)
    self.fc2 = torch.nn.Linear(120,84)
    self.fc3 = torch.nn.Linear(84,10)

  def forward(self, input):
    x = F.max_pool2d(F.relu(self.conv1(input)), (2,2))
    x = F.max_pool2d(F.relu(self.conv2(x)), 2)
    x = x.view(-1, self.num_flat_features(x))
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x
  def num_flat_features(self, x):
    size = x.size()[1:]
    num_features = 1
    for s in size:
      num_features *= s
    return num_features


In [22]:
class LSTMTagger(torch.nn.Module):
  def __init__(self, embedding_dim, hidden_dim, vocab_size, tagset_size):
    super(LSTMTagger, self).__init__()
    self.hidden_dim = hidden_dim
    self.word_embeddings = torch.nn.Embedding(vocab_size, embedding_dim)
    self.lstm =  torch.nn.LSTM(embedding_dim, hidden_dim)

    self.hidden2tag = torch.nn.Linear(hidden_dim, tagset_size)

  def forward(self, sentence):
    embeds = self.word_embeddings(sentence)
    lstm_out, _ = self.lstm(embeds.view(len(sentence), 1, -1))
    tag_space = self.hidden2tag(lstm_out.view(len(sentence), -1))
    tag_scores = F.log_softmax(tag_space, dim = 1)
    return tag_scores
