<a href="https://colab.research.google.com/github/macorony/NeuralNetwork/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

# Basic

In [19]:
z = torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [20]:
i = torch.ones((5,3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [21]:
torch.manual_seed(1729)
r1 = torch.rand(2,2)
print(r1)

r2 = torch.rand(2,2)
print(r2)

torch.manual_seed(1729)
r3 = torch.rand(2,2)
print(r3)

tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [22]:
ones = torch.ones(2,3)
print(ones)

twos = torch.ones(2,3) +2
print(twos)

threes = ones + twos
print(threes)
print(threes.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor([[4., 4., 4.],
        [4., 4., 4.]])
torch.Size([2, 3])


In [30]:
r = torch.rand(2,2) - 0.5 * 2
print("A random matrix, r: {}".format(r))
print("\nAbsolute value of r: {}".format(torch.abs(r)))
print("\nInverse sine of r: {}".format(torch.abs(r)))
print("\nDetermined of r: {}".format(torch.det(r)))
print("\nSingular Value decomposition of r: {}".format(torch.svd(r)))
print("\nAverage and standard deviation of r: {}".format(torch.std_mean(r)))
print("\nMaximum value of r: {}".format(torch.max(r)))

A random matrix, r: tensor([[-0.5885, -0.3161],
        [-0.9297, -0.4895]])

Absolute value of r: tensor([[0.5885, 0.3161],
        [0.9297, 0.4895]])

Inverse sine of r: tensor([[0.5885, 0.3161],
        [0.9297, 0.4895]])

Determined of r: -0.005855495110154152

Singular Value decomposition of r: torch.return_types.svd(
U=tensor([[-0.5365, -0.8439],
        [-0.8439,  0.5365]]),
S=tensor([1.2451, 0.0047]),
V=tensor([[ 0.8837, -0.4680],
        [ 0.4680,  0.8837]]))

Average and standard deviation of r: (tensor(0.2583), tensor(-0.5810))

Maximum value of r: -0.3161394000053406


# Autograd

In [35]:
x = torch.randn(1,10)
prev_h =torch.randn(1,20)
W_h = torch.randn(20,20)
W_x = torch.randn(20,10)

In [52]:
i2h = torch.mm(W_x, x.t())
h2h = torch.mm(W_h, prev_h.t())
next_h = i2h + h2h
next_h = next_h.tanh()

In [57]:
loss = next_h.sum()

In [50]:
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn