<a href="https://colab.research.google.com/github/macorony/NeuralNetwork/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

# Basic

In [ ]:
z = torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [ ]:
i = torch.ones((5,3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [ ]:
torch.manual_seed(1729)
r1 = torch.rand(2,2)
print(r1)

r2 = torch.rand(2,2)
print(r2)

torch.manual_seed(1729)
r3 = torch.rand(2,2)
print(r3)

tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [ ]:
ones = torch.ones(2,3)
print(ones)

twos = torch.ones(2,3) +2
print(twos)

threes = ones + twos
print(threes)
print(threes.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor([[4., 4., 4.],
        [4., 4., 4.]])
torch.Size([2, 3])


In [ ]:
r = torch.rand(2,2) - 0.5 * 2
print("A random matrix, r: {}".format(r))
print("\nAbsolute value of r: {}".format(torch.abs(r)))
print("\nInverse sine of r: {}".format(torch.abs(r)))
print("\nDetermined of r: {}".format(torch.det(r)))
print("\nSingular Value decomposition of r: {}".format(torch.svd(r)))
print("\nAverage and standard deviation of r: {}".format(torch.std_mean(r)))
print("\nMaximum value of r: {}".format(torch.max(r)))

A random matrix, r: tensor([[-0.5885, -0.3161],
        [-0.9297, -0.4895]])

Absolute value of r: tensor([[0.5885, 0.3161],
        [0.9297, 0.4895]])

Inverse sine of r: tensor([[0.5885, 0.3161],
        [0.9297, 0.4895]])

Determined of r: -0.005855495110154152

Singular Value decomposition of r: torch.return_types.svd(
U=tensor([[-0.5365, -0.8439],
        [-0.8439,  0.5365]]),
S=tensor([1.2451, 0.0047]),
V=tensor([[ 0.8837, -0.4680],
        [ 0.4680,  0.8837]]))

Average and standard deviation of r: (tensor(0.2583), tensor(-0.5810))

Maximum value of r: -0.3161394000053406


# Autograd

In [ ]:
x = torch.randn(1,10)
prev_h =torch.randn(1,20)
W_h = torch.randn(20,20)
W_x = torch.randn(20,10)

In [ ]:
i2h = torch.mm(W_x, x.t())
h2h = torch.mm(W_h, prev_h.t())
next_h = i2h + h2h
next_h = next_h.tanh()

In [ ]:
loss = next_h.sum()

# A pytorch model

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
class LeNet(nn.Module):
  def __init__(self):
    super(LeNet, self).__init__()
    # kernel
    self.conv1 = nn.Conv2d(1, 6, 3)
    self.conv2 = nn.Conv2d(6, 16, 3)
    # y = wx + b
    self.fc1 = nn.Linear(16*6*6, 120)
    self.fc2 = nn.Linear(120, 84)
    self.fc3 =nn.Linear(84, 10)

  def forward(self, x):
    x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))
    x = F.max_pool2d


In [6]:
m = nn.Linear(20, 30)
input = torch.randn(128, 20)
output = m(input)

In [8]:
output

tensor([[ 0.3137, -0.1909, -0.7118,  ...,  0.4352, -0.2289, -0.5751],
        [ 0.7176, -0.2809, -0.0642,  ...,  0.1343,  0.0056, -0.0945],
        [ 0.2266,  1.3283,  0.4204,  ..., -1.0705,  0.1867,  0.6012],
        ...,
        [-0.1744,  0.3702,  1.2319,  ..., -0.2679, -0.0900,  0.2909],
        [ 0.5830, -0.6409, -0.4386,  ...,  0.3439,  0.6090, -0.5480],
        [-0.2600,  0.0203, -0.8760,  ...,  0.0428, -0.4960,  0.2615]],
       grad_fn=<AddmmBackward0>)

In [20]:
m = nn.MaxPool2d(3, stride=2)
input = torch.randn(20, 16,20)
output = m(input)

In [21]:
output.shape

torch.Size([20, 7, 9])

# About pooling
1. The pooling operation involves sliding a two-dimensional filter over each channel of feature map and summarizing the features lying within the region by the filter.
2. A CNN model architecture is to have a number of convolution and pooling layers stacked one after the other
3. Pooling layer are used to reduce the dimensions of the feature maps. Thus, it reduce the numbers of parameters to learn and the amount of computation in the network.
4. The pooling layer summarises the features present in a region of the feature map generated by a convolution layer. So, further operation are performed on summarised features instead of precisely positioned features generated by the convolution layer.

## Types of pooling layer
1. Max pooling, a pooling operation to select the maximum element from the region of the feature map covered by the filter. Thus, the output after max-pooling layer would be a feature map containing the most prominent features of the previous map.
2. Average pooling computes the average of the elements present in the region of feature map covered by the filter.
3. Global pooling ?



In [22]:
from keras.models import Sequential
from keras.layers import MaxPooling2D

In [25]:
# Max pooling
import numpy as np
from keras.models import Sequential
from keras.layers import MaxPooling2D

image = np.array([])