<a href="https://colab.research.google.com/github/macorony/NeuralNetwork/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import math

In [6]:
x = torch.empty(3,4)
zeros = torch.zeros(2,3)
print(zeros)
ones = torch.ones(2,3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2,3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [13]:
torch.manual_seed(1729)
rand1 = torch.rand(2,3)
print(rand1)

rand2 = torch.rand(2,3)
print(rand2)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [7]:
torch.manual_seed(1729)
rand3 = torch.rand(2,3)
print(rand3)

rand4 = torch.rand(2,3)
print(rand4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [12]:
x = torch.empty(2,2,2,2,2,2)
print(x.shape)
print(x)

torch.Size([2, 2, 2, 2, 2, 2])
tensor([[[[[[ 1.1532e+30,  3.1615e-41],
            [ 1.1039e+30,  3.1615e-41]],

           [[ 1.1210e-43,  0.0000e+00],
            [ 8.9683e-44,  0.0000e+00]]],


          [[[-1.8237e+31,  3.1619e-41],
            [ 1.1518e+30,  3.1615e-41]],

           [[ 0.0000e+00,  1.8436e+25],
            [ 0.0000e+00,  0.0000e+00]]]],



         [[[[ 5.7453e-44,  0.0000e+00],
            [ 0.0000e+00,  3.9045e+30]],

           [[ 2.0179e-43,  0.0000e+00],
            [ 2.6905e-43,  0.0000e+00]]],


          [[[ 1.1532e+30,  3.1615e-41],
            [ 1.8777e-43,  0.0000e+00]],

           [[ 0.0000e+00,  0.0000e+00],
            [ 0.0000e+00,  0.0000e+00]]]]],




        [[[[[ 0.0000e+00,  0.0000e+00],
            [ 7.7052e+31,  7.2148e+22]],

           [[ 1.5766e-19,  1.0256e-08],
            [ 1.6802e-04,  3.0957e+12]]],


          [[[ 2.7095e-09,  6.7140e-07],
            [ 2.7001e-06,  1.2962e+16]],

           [[ 2.1707e-18,  7.0952e+22],
           

In [24]:
a = torch.tensor([
    [1,1],
    [1,1]
    ])
print(a)

b = torch.tensor((2,2,2,4))
print(b)

c = torch.tensor(((1,2), [3,4]))
print(c)

tensor([[1, 1],
        [1, 1]])
tensor([2, 2, 2, 4])
tensor([[1, 2],
        [3, 4]])


In [30]:
d = torch.ones((2,3))
print(d.shape)

torch.Size([2, 3])


In [28]:
torch.tensor((2,3)).shape

torch.Size([2])

In [35]:
torch.rand(2,3)

tensor([[0.0703, 0.5105, 0.9451],
        [0.2359, 0.1979, 0.3327]])

In [38]:
x = torch.empty(2,2,4)
x

tensor([[[1.5766e-19, 1.0256e-08, 1.6802e-04, 3.0957e+12],
         [2.7095e-09, 6.5566e-10, 1.0919e-05, 1.3032e+16]],

        [[2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31],
         [7.2708e+31, 5.0778e+31, 3.2608e-12, 1.7728e+28]]])

In [39]:
torch.empty_like(x)

tensor([[[ 1.5351e+29,  3.1615e-41, -4.2862e-13,  4.3997e-41],
         [ 1.4013e-45,  0.0000e+00,  2.2421e-44,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [40]:
torch.zeros_like(x)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [41]:
torch.ones_like(x)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [44]:
torch.rand_like(x)

tensor([[[0.6146, 0.5999, 0.5013, 0.9397],
         [0.8656, 0.5207, 0.6865, 0.3614]],

        [[0.6493, 0.2633, 0.4762, 0.0548],
         [0.2024, 0.5731, 0.7191, 0.4067]]])

In [46]:
a = torch.ones((2,3), dtype = torch.int16)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [51]:
b = torch.rand((2,3), dtype = torch.float64)
b

tensor([[0.0364, 0.8640, 0.2031],
        [0.0591, 0.0906, 0.8456]], dtype=torch.float64)

In [54]:
c = b.to(torch.int16)
c

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)

In [75]:
ones = torch.zeros((2,2)) + 1
ones

tensor([[1., 1.],
        [1., 1.]])

In [69]:
twos = torch.ones((2,2)) + 1
twos

tensor([[2., 2.],
        [2., 2.]])

In [62]:
(torch.ones(2,2) * 7 - 1) / 2

tensor([[3., 3.],
        [3., 3.]])

In [73]:
fours = twos ** 2

In [66]:
twos ** 0.5

tensor([[1.4142, 1.4142, 1.4142, 1.4142],
        [1.4142, 1.4142, 1.4142, 1.4142],
        [1.4142, 1.4142, 1.4142, 1.4142]])

In [71]:
power2 = twos ** torch.tensor([[1,2], [3,4]])

In [76]:
fives = ones + fours

In [79]:
rand = torch.rand(2,4)
rand * (torch.ones(1,4) * 2)

tensor([[1.4032, 1.3653, 1.8827, 0.8920],
        [1.8577, 1.2585, 1.2528, 0.9407]])

In [82]:
torch.ones(1,4).shape

torch.Size([1, 4])

In [83]:
rand.shape

torch.Size([2, 4])

In [100]:
a = torch.ones(4,3,2)
a * torch.rand(1,1,2)

tensor([[[0.1067, 0.6171],
         [0.1067, 0.6171],
         [0.1067, 0.6171]],

        [[0.1067, 0.6171],
         [0.1067, 0.6171],
         [0.1067, 0.6171]],

        [[0.1067, 0.6171],
         [0.1067, 0.6171],
         [0.1067, 0.6171]],

        [[0.1067, 0.6171],
         [0.1067, 0.6171],
         [0.1067, 0.6171]]])

In [101]:
a = torch.rand(2,4)

In [106]:
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

tensor([[0.6354, 0.5252, 0.6931, 0.0412],
        [0.8552, 0.2873, 0.8335, 0.0660]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.5000, 0.5000, 0.5000, 0.0412],
        [0.5000, 0.2873, 0.5000, 0.0660]])


In [108]:
angles = torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])

In [112]:
print(angles)
print(torch.sin(angles))
print(torch.asin(angles))

tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.9033,    nan,    nan])


In [113]:
a = torch.tensor([1,5,11])
b = torch.tensor([2,7,10])
torch.bitwise_xor(a, b)

tensor([3, 2, 1])

In [114]:
print(torch.eq(a, b))

tensor([False, False, False])


In [133]:
c = torch.tensor([[1,2], [3,4]], dtype=torch.float64)

In [135]:
print(torch.max(c))
print(torch.max(c).item())
print(torch.mean(c))
print(torch.std(c))
print(torch.prod(c))

tensor(4., dtype=torch.float64)
4.0
tensor(2.5000, dtype=torch.float64)
tensor(1.2910, dtype=torch.float64)
tensor(24., dtype=torch.float64)


In [136]:
# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])
v2 = torch.tensor([0., 1., 0.])
m1 = torch.rand(2,2)
m2 = torch.tensor([[3.,0.], [0.,3.]])

In [139]:
print(torch.cross(v2, v1))
print(torch.matmul(m1, m2))

tensor([ 0.,  0., -1.])
tensor([[2.1246, 2.7238],
        [2.0354, 2.5338]])


In [142]:
a[1]

tensor(5)