<a href="https://colab.research.google.com/github/macorony/NeuralNetwork/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import torch
import math

In [56]:
x = torch.empty(3,4)
zeros = torch.zeros(2,3)
print(zeros)
ones = torch.ones(2,3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2,3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [57]:
torch.manual_seed(1729)
rand1 = torch.rand(2,3)
print(rand1)

rand2 = torch.rand(2,3)
print(rand2)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [58]:
torch.manual_seed(1729)
rand3 = torch.rand(2,3)
print(rand3)

rand4 = torch.rand(2,3)
print(rand4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [59]:
x = torch.empty(2,2,2,2,2,2)
print(x.shape)
print(x)

torch.Size([2, 2, 2, 2, 2, 2])
tensor([[[[[[-1.3422e+28,  4.3810e-41],
            [-1.8313e+28,  4.3810e-41]],

           [[ 2.3379e-31,  4.3810e-41],
            [ 4.3479e-31,  4.3810e-41]]],


          [[[-1.5395e+28,  4.3810e-41],
            [-1.8419e+28,  4.3810e-41]],

           [[-9.5663e+27,  4.3810e-41],
            [-1.9783e+28,  4.3810e-41]]]],



         [[[[-1.7852e+28,  4.3810e-41],
            [-1.0205e+28,  4.3810e-41]],

           [[-2.1533e+27,  4.3810e-41],
            [-5.4992e+27,  4.3810e-41]]],


          [[[-1.9280e+28,  4.3810e-41],
            [-1.1858e-11,  4.3810e-41]],

           [[ 6.9865e-31,  4.3810e-41],
            [-1.7834e+28,  4.3810e-41]]]]],




        [[[[[-1.7662e+28,  4.3810e-41],
            [ 1.7883e-32,  4.3810e-41]],

           [[ 4.7548e-32,  4.3810e-41],
            [ 1.8179e-32,  4.3810e-41]]],


          [[[ 1.8140e-32,  4.3810e-41],
            [ 2.9556e-31,  4.3810e-41]],

           [[ 0.0000e+00,  0.0000e+00],
           

In [60]:
a = torch.tensor([
    [1,1],
    [1,1]
    ])
print(a)

b = torch.tensor((2,2,2,4))
print(b)

c = torch.tensor(((1,2), [3,4]))
print(c)

tensor([[1, 1],
        [1, 1]])
tensor([2, 2, 2, 4])
tensor([[1, 2],
        [3, 4]])


In [61]:
d = torch.ones((2,3))
print(d.shape)

torch.Size([2, 3])


In [62]:
torch.tensor((2,3)).shape

torch.Size([2])

In [63]:
torch.rand(2,3)

tensor([[0.6128, 0.1519, 0.0453],
        [0.5035, 0.9978, 0.3884]])

In [64]:
x = torch.empty(2,2,4)
x

tensor([[[ 0.0000e+00,  0.0000e+00, -7.6920e+08,  3.1906e-41],
         [-2.4918e+07,  3.1906e-41,  1.0406e-26,  4.3810e-41]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [65]:
torch.empty_like(x)

tensor([[[-3.3104e+28,  4.3810e-41, -8.5610e+08,  3.1906e-41],
         [-1.0321e+09,  3.1906e-41, -4.1563e+08,  3.1906e-41]],

        [[ 0.0000e+00,  0.0000e+00, -1.5497e+08,  3.1906e-41],
         [-2.4918e+07,  3.1906e-41, -1.3512e-11,  4.3810e-41]]])

In [66]:
torch.zeros_like(x)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [67]:
torch.ones_like(x)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [68]:
torch.rand_like(x)

tensor([[[0.6929, 0.1703, 0.1384, 0.4759],
         [0.7481, 0.0361, 0.5062, 0.8469]],

        [[0.2588, 0.2707, 0.4115, 0.6839],
         [0.0703, 0.5105, 0.9451, 0.2359]]])

In [69]:
a = torch.ones((2,3), dtype = torch.int16)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [70]:
b = torch.rand((2,3), dtype = torch.float64)
b

tensor([[0.5835, 0.9164, 0.0106],
        [0.9249, 0.4919, 0.1947]], dtype=torch.float64)

In [71]:
c = b.to(torch.int16)
c

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)

In [72]:
ones = torch.zeros((2,2)) + 1
ones

tensor([[1., 1.],
        [1., 1.]])

In [73]:
twos = torch.ones((2,2)) + 1
twos

tensor([[2., 2.],
        [2., 2.]])

In [74]:
(torch.ones(2,2) * 7 - 1) / 2

tensor([[3., 3.],
        [3., 3.]])

In [75]:
fours = twos ** 2

In [76]:
twos ** 0.5

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

In [77]:
power2 = twos ** torch.tensor([[1,2], [3,4]])

In [78]:
fives = ones + fours

In [79]:
rand = torch.rand(2,4)
rand * (torch.ones(1,4) * 2)

tensor([[0.9524, 0.1096, 0.4049, 1.1461],
        [1.4382, 0.8134, 1.4602, 1.2551]])

In [80]:
torch.ones(1,4).shape

torch.Size([1, 4])

In [81]:
rand.shape

torch.Size([2, 4])

In [82]:
a = torch.ones(4,3,2)
a * torch.rand(1,1,2)

tensor([[[0.7357, 0.0381],
         [0.7357, 0.0381],
         [0.7357, 0.0381]],

        [[0.7357, 0.0381],
         [0.7357, 0.0381],
         [0.7357, 0.0381]],

        [[0.7357, 0.0381],
         [0.7357, 0.0381],
         [0.7357, 0.0381]],

        [[0.7357, 0.0381],
         [0.7357, 0.0381],
         [0.7357, 0.0381]]])

In [83]:
a = torch.rand(2,4)

In [84]:
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

tensor([[0.2138, 0.5395, 0.3686, 0.4007],
        [0.7220, 0.8217, 0.2612, 0.7375]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.2138, 0.5000, 0.3686, 0.4007],
        [0.5000, 0.5000, 0.2612, 0.5000]])


In [85]:
angles = torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])

In [86]:
print(angles)
print(torch.sin(angles))
print(torch.asin(angles))

tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.9033,    nan,    nan])


In [87]:
a = torch.tensor([1,5,11])
b = torch.tensor([2,7,10])
torch.bitwise_xor(a, b)

tensor([3, 2, 1])

In [88]:
print(torch.eq(a, b))

tensor([False, False, False])


In [89]:
c = torch.tensor([[1,2], [3,4]], dtype=torch.float64)

In [90]:
print(torch.max(c))
print(torch.max(c).item())
print(torch.mean(c))
print(torch.std(c))
print(torch.prod(c))

tensor(4., dtype=torch.float64)
4.0
tensor(2.5000, dtype=torch.float64)
tensor(1.2910, dtype=torch.float64)
tensor(24., dtype=torch.float64)


In [91]:
# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])
v2 = torch.tensor([0., 1., 0.])
m1 = torch.rand(2,2)
m2 = torch.tensor([[3.,0.], [0.,3.]])

In [92]:
print(torch.cross(v2, v1))
print(torch.matmul(m1, m2))

tensor([ 0.,  0., -1.])
tensor([[2.4985, 2.5332],
        [0.8822, 1.1364]])


In [93]:
a[1]

tensor(5)

In [94]:
a = torch.ones(2,2)
b = a

In [95]:
a[0][1] = 5

In [96]:
b

tensor([[1., 5.],
        [1., 1.]])

In [97]:
a = torch.ones(2,2)
b = a.clone()

In [98]:
assert b is not a

In [99]:
a[0,1] = 4

In [100]:
a

tensor([[1., 4.],
        [1., 1.]])

In [101]:
b

tensor([[1., 1.],
        [1., 1.]])

In [102]:
a = torch.rand(2, 2, requires_grad=True)
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

tensor([[0.4567, 0.0649],
        [0.6677, 0.7826]], requires_grad=True)
tensor([[0.4567, 0.0649],
        [0.6677, 0.7826]], grad_fn=<CloneBackward0>)
tensor([[0.4567, 0.0649],
        [0.6677, 0.7826]])


In [103]:
if torch.cuda.is_available():
  gpu_rand = torch.rand(2,2, device="cuda")
  print(gpu_rand)
else:
  print("GPU is not available")

GPU is not available


In [104]:
if torch.cuda.is_available():
  my_device = torch.device("cuda")
else:
  my_device = torch.device("cpu")

x = torch.rand(2,2, device=my_device)
print(x)

tensor([[0.1332, 0.0023],
        [0.4945, 0.3857]])


In [105]:
torch.cuda.device_count()

0

In [106]:
x = torch.rand(2,2)
# y = torch.rand(2,2,device= "cuda")


In [111]:
a = torch.rand(3,22,22)
b = a.unsqueeze(0)
print(a.shape)
print(b.shape)

torch.Size([3, 22, 22])
torch.Size([1, 3, 22, 22])


In [120]:
a = torch.rand(1,20)
print(a.shape)
print(a)

torch.Size([1, 20])
tensor([[0.3559, 0.5349, 0.6105, 0.0903, 0.2810, 0.7065, 0.1023, 0.9444, 0.1310,
         0.5688, 0.7254, 0.6714, 0.7146, 0.2126, 0.0874, 0.7276, 0.9114, 0.4551,
         0.1802, 0.6767]])


In [121]:
b = a.squeeze(0)
print(b.shape)
print(b)

torch.Size([20])
tensor([0.3559, 0.5349, 0.6105, 0.0903, 0.2810, 0.7065, 0.1023, 0.9444, 0.1310,
        0.5688, 0.7254, 0.6714, 0.7146, 0.2126, 0.0874, 0.7276, 0.9114, 0.4551,
        0.1802, 0.6767])


In [123]:
out3d = torch.rand(6,20,20)
print(out3d.shape)

torch.Size([6, 20, 20])


In [128]:
out1d = out3d.reshape(6*20*20,)
print(out1d.shape)

torch.Size([2400])


In [129]:
torch.reshape(out3d, (6*20*20,))

tensor([0.2152, 0.2835, 0.6836,  ..., 0.9107, 0.7800, 0.8701])

In [133]:
import numpy as np
array = np.ones((2,2))
to_tensor = torch.from_numpy(array)
print(to_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [136]:
a_tensor = torch.rand(2,3)
to_array = a_tensor.numpy()
print(type(to_array))

<class 'numpy.ndarray'>
