<a href="https://colab.research.google.com/github/macorony/NeuralNetwork/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import math

In [2]:
x = torch.empty(3,4)
zeros = torch.zeros(2,3)
print(zeros)
ones = torch.ones(2,3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2,3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [3]:
torch.manual_seed(1729)
rand1 = torch.rand(2,3)
print(rand1)

rand2 = torch.rand(2,3)
print(rand2)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [4]:
torch.manual_seed(1729)
rand3 = torch.rand(2,3)
print(rand3)

rand4 = torch.rand(2,3)
print(rand4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [5]:
x = torch.empty(2,2,2,2,2,2)
print(x.shape)
print(x)

torch.Size([2, 2, 2, 2, 2, 2])
tensor([[[[[[ 1.0570e+21,  1.7265e-07],
            [ 2.1707e-18,  4.5447e+30]],

           [[ 7.0062e+22,  2.1715e-18],
            [ 4.5447e+30,  7.0062e+22]]],


          [[[ 2.1707e-18,  1.9284e+31],
            [ 3.2314e-18,  3.8654e-05]],

           [[ 3.2874e+21,  1.2859e-11],
            [ 1.0563e-05,  1.3149e+22]]]],



         [[[[ 3.3975e+21,  6.3078e-10],
            [ 4.2315e+21,  3.3644e+21]],

           [[ 2.3881e-18,  3.1360e+27],
            [ 7.0800e+31,  3.1095e-18]]],


          [[[ 4.7851e+22,  2.8826e+32],
            [ 4.4248e+30,  7.2442e+22]],

           [[ 2.3086e-12,  7.2646e+22],
            [ 7.2250e+28,  1.5766e-19]]]]],




        [[[[[ 6.3376e-10,  2.1707e-18],
            [ 7.2128e+22,  2.1715e-18]],

           [[ 1.6595e-07,  1.0527e-11],
            [ 7.7201e-10,  4.3208e-05]]],


          [[[ 4.2111e-11,  4.2422e-08],
            [ 2.9573e-18,  4.3941e-41]],

           [[ 1.4013e-45,  0.0000e+00],
           

In [6]:
a = torch.tensor([
    [1,1],
    [1,1]
    ])
print(a)

b = torch.tensor((2,2,2,4))
print(b)

c = torch.tensor(((1,2), [3,4]))
print(c)

tensor([[1, 1],
        [1, 1]])
tensor([2, 2, 2, 4])
tensor([[1, 2],
        [3, 4]])


In [7]:
d = torch.ones((2,3))
print(d.shape)

torch.Size([2, 3])


In [8]:
torch.tensor((2,3)).shape

torch.Size([2])

In [9]:
torch.rand(2,3)

tensor([[0.6128, 0.1519, 0.0453],
        [0.5035, 0.9978, 0.3884]])

In [10]:
x = torch.empty(2,2,4)
x

tensor([[[ 0.0000e+00,  0.0000e+00, -1.5497e+08,  3.1906e-41],
         [-2.4918e+07,  3.1906e-41, -3.6257e-12,  4.3810e-41]],

        [[ 1.4013e-45,  0.0000e+00,  8.4078e-45,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [11]:
torch.empty_like(x)

tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])

In [12]:
torch.zeros_like(x)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
torch.ones_like(x)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
torch.rand_like(x)

tensor([[[0.6929, 0.1703, 0.1384, 0.4759],
         [0.7481, 0.0361, 0.5062, 0.8469]],

        [[0.2588, 0.2707, 0.4115, 0.6839],
         [0.0703, 0.5105, 0.9451, 0.2359]]])

In [15]:
a = torch.ones((2,3), dtype = torch.int16)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [16]:
b = torch.rand((2,3), dtype = torch.float64)
b

tensor([[0.5835, 0.9164, 0.0106],
        [0.9249, 0.4919, 0.1947]], dtype=torch.float64)

In [17]:
c = b.to(torch.int16)
c

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)

In [18]:
ones = torch.zeros((2,2)) + 1
ones

tensor([[1., 1.],
        [1., 1.]])

In [19]:
twos = torch.ones((2,2)) + 1
twos

tensor([[2., 2.],
        [2., 2.]])

In [20]:
(torch.ones(2,2) * 7 - 1) / 2

tensor([[3., 3.],
        [3., 3.]])

In [21]:
fours = twos ** 2

In [22]:
twos ** 0.5

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

In [23]:
power2 = twos ** torch.tensor([[1,2], [3,4]])

In [24]:
fives = ones + fours

In [25]:
rand = torch.rand(2,4)
rand * (torch.ones(1,4) * 2)

tensor([[0.9524, 0.1096, 0.4049, 1.1461],
        [1.4382, 0.8134, 1.4602, 1.2551]])

In [26]:
torch.ones(1,4).shape

torch.Size([1, 4])

In [27]:
rand.shape

torch.Size([2, 4])

In [28]:
a = torch.ones(4,3,2)
a * torch.rand(1,1,2)

tensor([[[0.7357, 0.0381],
         [0.7357, 0.0381],
         [0.7357, 0.0381]],

        [[0.7357, 0.0381],
         [0.7357, 0.0381],
         [0.7357, 0.0381]],

        [[0.7357, 0.0381],
         [0.7357, 0.0381],
         [0.7357, 0.0381]],

        [[0.7357, 0.0381],
         [0.7357, 0.0381],
         [0.7357, 0.0381]]])

In [29]:
a = torch.rand(2,4)

In [30]:
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

tensor([[0.2138, 0.5395, 0.3686, 0.4007],
        [0.7220, 0.8217, 0.2612, 0.7375]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.2138, 0.5000, 0.3686, 0.4007],
        [0.5000, 0.5000, 0.2612, 0.5000]])


In [31]:
angles = torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])

In [32]:
print(angles)
print(torch.sin(angles))
print(torch.asin(angles))

tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.9033,    nan,    nan])


In [33]:
a = torch.tensor([1,5,11])
b = torch.tensor([2,7,10])
torch.bitwise_xor(a, b)

tensor([3, 2, 1])

In [34]:
print(torch.eq(a, b))

tensor([False, False, False])


In [35]:
c = torch.tensor([[1,2], [3,4]], dtype=torch.float64)

In [36]:
print(torch.max(c))
print(torch.max(c).item())
print(torch.mean(c))
print(torch.std(c))
print(torch.prod(c))

tensor(4., dtype=torch.float64)
4.0
tensor(2.5000, dtype=torch.float64)
tensor(1.2910, dtype=torch.float64)
tensor(24., dtype=torch.float64)


In [37]:
# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])
v2 = torch.tensor([0., 1., 0.])
m1 = torch.rand(2,2)
m2 = torch.tensor([[3.,0.], [0.,3.]])

In [38]:
print(torch.cross(v2, v1))
print(torch.matmul(m1, m2))

tensor([ 0.,  0., -1.])
tensor([[2.4985, 2.5332],
        [0.8822, 1.1364]])


<ipython-input-38-a286491a2eb3>:1: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at ../aten/src/ATen/native/Cross.cpp:62.)
  print(torch.cross(v2, v1))


In [39]:
a[1]

tensor(5)

In [40]:
a = torch.ones(2,2)
b = a

In [41]:
a[0][1] = 5

In [42]:
b

tensor([[1., 5.],
        [1., 1.]])

In [43]:
a = torch.ones(2,2)
b = a.clone()

In [44]:
assert b is not a

In [45]:
a[0,1] = 4

In [46]:
a

tensor([[1., 4.],
        [1., 1.]])

In [47]:
b

tensor([[1., 1.],
        [1., 1.]])

In [48]:
a = torch.rand(2, 2, requires_grad=True)
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

tensor([[0.4567, 0.0649],
        [0.6677, 0.7826]], requires_grad=True)
tensor([[0.4567, 0.0649],
        [0.6677, 0.7826]], grad_fn=<CloneBackward0>)
tensor([[0.4567, 0.0649],
        [0.6677, 0.7826]])


In [49]:
if torch.cuda.is_available():
  gpu_rand = torch.rand(2,2, device="cuda")
  print(gpu_rand)
else:
  print("GPU is not available")

GPU is not available


In [50]:
if torch.cuda.is_available():
  my_device = torch.device("cuda")
else:
  my_device = torch.device("cpu")

x = torch.rand(2,2, device=my_device)
print(x)

tensor([[0.1332, 0.0023],
        [0.4945, 0.3857]])


In [51]:
torch.cuda.device_count()

0

In [54]:
x = torch.rand(2,2)
# y = torch.rand(2,2,device= "cuda")


In [ ]:
a = torch.rand(3,22,22)
b = a.unsqueeze(0)
